### PR TITLE
Fixes absolute messages in non-prefixed translator

### LINKED ISSUE #126: Absolute messages in non-prefixed translator does not work
@fprochazka i should be able to write failing test & fix it

### PR DESCRIPTION
**Pull request by Lexinek**
Fixes #126 
Possible fix to #114 (not tested) @medhi please would you mind try it out?

### CODE REVIEW

**Comment by medhi** [comment]
I would, but I don't know how to test a pull request, can you help me?

**Comment by Lexinek** [comment]
@medhi you can use the pull request repository instead of the vendor's default one and run `composer update` (thats the way i would do it), update your `composer.json` like this:
```
{
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/Lexinek/Translation"
		}
	],
	"require": {
		"kdyby/translation": "@dev"
	}
}
```

**Comment by medhi** [comment]
Thanks. Tested and seems fixed.

**Comment by Lexinek** [comment]
@fprochazka Possible to merge, so i can delete repository Lexinek/Translation please?

**Comment by fprochazka** [comment]
Yeah, this looks reasonable. Thank you guys!

**Pull request merged**
