### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by nofutur3**
translation section should be placed in parameters

### CODE REVIEW

**Comment by vysinsky** [comment]
Why? It is extension configuration. The original version is correct.

**Comment by nofutur3** [comment]
It returns exception "found section ... but corresponding extensions are missing", isn't it better to have it under parameters section working without additional improvements?

**Comment by vysinsky** [comment]
Did you register the extension in the config?

```
extensions:
    translation: Kdyby\Translation\DI\TranslationExtension
```

In case you'll add it in parameters it won't have any effect to the extension.

**Comment by nofutur3** [comment]
Of course I did register the extension.
I moved it under parameters and it's working. Using nette 2.3 but I believe it would be the same since 2.1.

**Comment by vysinsky** [comment]
Ok. Maybe I am wrong and I am sorry if it is the case. Let's wait for @fprochazka :)

**Comment by enumag** [comment]
No it should not be under parameters. The exception "found section ... but corresponding extensions are missing" means that there probably is a typo.

**Comment by nofutur3** [comment]
Well, you are probably right @enumag but I was surprised it worked placed in the parameters section. Anyway I tried to move it to it's own section and it works now, so I was wrong.

**Comment by enumag** [comment]
It should not have any meaning in the parameters section. Try removing it from both the parameters and the separate section, I guess it will still work.

Also close this issue please.

**Comment by fprochazka** [comment]
No it shouldn't.

**Comment by fprochazka** [comment]
Thank you for the effort tho :)

**Pull request closed without merging**
