### PR TITLE
Refactored DI extension

### PR DESCRIPTION
**Pull request by enumag**
Same refactoring as https://github.com/Kdyby/Console/pull/26.

I also removed support for nette.latte. I think it was never used in 2.2 stable.

### CODE REVIEW

**Comment by enumag** [comment]
Failed travis is unrelated.

**Comment by fprochazka** [comment]
Untill it's removed from nette, I don't wanna remove the BC from extension.

**Comment by enumag** [comment]
@fprochazka Understood, fixed, rebased. ;-)

**Comment by enumag** [comment]
ping @fprochazka

**Comment by enumag** [comment]
@fprochazka Also I'd really appriciate a stable version after this is merged. Current stable TranslationExtension doesn't work at all without latte (it's fixed in master). ;-)

**Comment by fprochazka** [comment]
Thank you!

**Pull request closed without merging**
