### PR TITLE
Allow Symfony 3.x

### LINKED ISSUE #118: Compatibility with Symfony Translation 3.x

### PR DESCRIPTION
**Pull request by enumag**
[Closes #118]

### CODE REVIEW

**Comment by enumag** [comment]
@fprochazka The failing test is the same one as in master so it's unrelated to this pull request.

**Comment by aleswita** [comment]
It's posibble to add dependecy on nette/php-generator ~3.0?

**Comment by enumag** [comment]
@aleswita That should be a separate PR in my opinion. Feel free to send one.

**Comment by fprochazka** [comment]
@enumag Thank you!

**Comment by fprochazka** [comment]
@aleswita added https://github.com/Kdyby/Translation/commit/0400e8bf266b8b57209f4f65c7dd853abcedae6c :)

**Pull request closed without merging**
