### PR TITLE
Fix Nette 2.4 compatibility

### PR DESCRIPTION
**Pull request by romanmatyus**

### CODE REVIEW

**Comment by enumag** [comment]
@romanmatyus You should have force-pushed the branch instead of creating new PR.

**Comment by romanmatyus** [comment]
What? Why?

**Comment by jakubvojacek** [comment]
What is the status of this PR, can it be merged?

**Comment by enumag** [comment]
@romanmatyus To avoid creating multiple PRs (#110 and this one).

@jakubvojacek The status is that the maintainer has exams right now so it might take a while.

**Comment by tomaj** [comment]
👍  waiting for merge

**Comment by fprochazka** [comment]
Thank you, merged https://github.com/Kdyby/Translation/commit/8c9aa8174610b8c05523d96d2a8bda0731a1e62f

**Pull request closed without merging**
